/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import java.sql.*;
import javax.swing.JOptionPane;
import conexiones.Conexion;
import java.awt.Color;

public class agregarPaciente extends javax.swing.JInternalFrame {
    
    private boolean Comprobar(){
        int c = 0;
        if(textNombre.getText().isEmpty()){
            textNombre.setBackground(Color.pink);
            jLabel10.setVisible(true);
            c++;
        }
        if(textApellido.getText().isEmpty()){
            textApellido.setBackground(Color.pink);
            jLabel10.setVisible(true);
            c++;
        }
        if(textCedula.getText().isEmpty()){
            textCedula.setBackground(Color.pink);
            jLabel10.setVisible(true);
            c++;
        }
        if(jTextAreaDireccion.getText().isEmpty()){
            jTextAreaDireccion.setBackground(Color.pink);
            jLabel10.setVisible(true);
            c++;
        }
        if(jTextdescripcion.getText().isEmpty()){
            jTextdescripcion.setBackground(Color.pink);
            jLabel10.setVisible(true);
            c++;
        }
        if(((String)jComboBox1.getSelectedItem()).equals("Familiar de Trabajador")){
            if(CedulaT.getText().isEmpty()){
                c++;
                CedulaT.setBackground(Color.pink);
                jLabel10.setVisible(true);
            }
            if(!CedulaT.getText().matches("\\d{1,}")){
                c++;
                CedulaT.setBackground(Color.pink);
                JOptionPane.showMessageDialog(this,"No introduzca letras o simbolos en la cedula");
            }
        }
        if(((String)jComboBox1.getSelectedItem()).equals("Personal Empresa que hace vida en las instalaciones")||((String)jComboBox1.getSelectedItem()).equals("Otras Instituciones del estado")){
            if(empresa.getText().isEmpty()){
                c++;
                empresa.setBackground(Color.pink);
                jLabel10.setVisible(true);
            }
        }
        if(((String)jComboBox1.getSelectedItem()).equals("Trabajador Titular")){
            if(Departamento.getText().isEmpty()){
                c++;
                Departamento.setBackground(Color.pink);
                jLabel10.setVisible(true);
            }
        }
        return c==0;
    }
    private void vaciar(){
        textNombre.setText("");
        textApellido.setText("");
        textCedula.setText("");
        textTelefono.setText("");
        jTextdescripcion.setText("");
        jTextAreaDireccion.setText("");
        CedulaT.setText("");
        empresa.setText("");
        Departamento.setText("");
    }
    public agregarPaciente() {
        initComponents();
        jLabel10.setVisible(false);
        CedulaT.setEnabled(false);
        empresa.setEnabled(false);
    }
    public agregarPaciente(String Cedula) {
        initComponents();
        jLabel10.setVisible(false);
        textCedula.setText(Cedula);
        CedulaT.setEnabled(false);
        empresa.setEnabled(false);
    }
    private boolean BuscarCedula(String cedula){
        try {
            Connection con;
            Conexion conect = new Conexion(Ventana.getruta());
            con = conect.getConnection();
            int id = 0;
            String sql = "select Id_paciente from Pacientes where cedula='"+cedula+"'";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while(rs.next()){
                id = Integer.parseInt(rs.getString("Id_paciente"));  
            }
            con.close();
            return id!=0;
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this,"error al buscar"+e);
            return false;
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        radioM = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        textCedula = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextdescripcion = new javax.swing.JTextArea();
        textApellido = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        textTelefono = new javax.swing.JTextField();
        textNombre = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaDireccion = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        radioF = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        CedulaT = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        empresa = new javax.swing.JTextField();
        Departamento = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();

        buttonGroup1.add(radioM);
        buttonGroup1.add(radioF);

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setIconifiable(true);
        setTitle("Registrar paciente");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/imageneseiconos/agregar.png"))); // NOI18N
        setOpaque(true);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("debe rellenar todos lo campos");

        radioM.setForeground(new java.awt.Color(255, 255, 255));
        radioM.setText("Masculino");
        radioM.setOpaque(false);
        radioM.setSelected(true);

        radioM.setActionCommand("Masculino");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Registro de pacientes");

        textCedula.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textCedula.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textCedulaMouseClicked(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Descripcion:");

        jScrollPane2.setForeground(new java.awt.Color(255, 255, 255));

        jTextdescripcion.setColumns(20);
        jTextdescripcion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextdescripcion.setLineWrap(true);
        jTextdescripcion.setRows(5);
        jTextdescripcion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextdescripcionMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTextdescripcion);

        textApellido.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textApellido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textApellidoMouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Direccion:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("CI:");

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("registrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre: ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Apellido:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Telefono:");

        textTelefono.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        textNombre.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textNombreMouseClicked(evt);
            }
        });
        textNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNombreActionPerformed(evt);
            }
        });

        jScrollPane1.setForeground(new java.awt.Color(255, 255, 255));

        jTextAreaDireccion.setColumns(20);
        jTextAreaDireccion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextAreaDireccion.setLineWrap(true);
        jTextAreaDireccion.setRows(5);
        jTextAreaDireccion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextAreaDireccionMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTextAreaDireccion);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Sexo:");

        radioF.setForeground(new java.awt.Color(255, 255, 255));
        radioF.setText("Femenino");
        radioF.setOpaque(false);
        radioF.setActionCommand("Femenino");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Cedula Titular:");

        CedulaT.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        CedulaT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CedulaTMouseClicked(evt);
            }
        });
        CedulaT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CedulaTActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Empresa para la que trabaja:");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Aspecto");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Trabajador Titular", "Familiar de Trabajador", "Personal Empresa que hace vida en las instalaciones", "Otras Instituciones del estado", "Casos Comunitarios" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        empresa.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        empresa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                empresaMouseClicked(evt);
            }
        });
        empresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empresaActionPerformed(evt);
            }
        });

        Departamento.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Departamento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DepartamentoMouseClicked(evt);
            }
        });
        Departamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DepartamentoActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Area de Adscripcion en Bolipuertos ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(radioM)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(radioF))
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(textTelefono, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel12)
                                        .addComponent(jLabel13)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jButton1)
                                            .addComponent(CedulaT, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(empresa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(jLabel9)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(textNombre, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(textApellido, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(textCedula, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Departamento, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel12)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(textNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(empresa, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel14)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(CedulaT, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Departamento, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(radioM)
                            .addComponent(radioF))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(jLabel7)
                        .addGap(7, 7, 7)
                        .addComponent(textTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jScrollPane3.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextdescripcionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextdescripcionMouseClicked
        jTextdescripcion.setBackground(Color.white);
    }//GEN-LAST:event_jTextdescripcionMouseClicked

    private void textNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNombreActionPerformed

    private void textNombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textNombreMouseClicked
        textNombre.setBackground(Color.white);
    }//GEN-LAST:event_textNombreMouseClicked

    private void textApellidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textApellidoMouseClicked
        textApellido.setBackground(Color.white);
    }//GEN-LAST:event_textApellidoMouseClicked

    private void textCedulaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textCedulaMouseClicked
        textCedula.setBackground(Color.white);
    }//GEN-LAST:event_textCedulaMouseClicked

    private void jTextAreaDireccionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextAreaDireccionMouseClicked
        jTextAreaDireccion.setBackground(Color.white);
    }//GEN-LAST:event_jTextAreaDireccionMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        if(Comprobar()){
            if(textCedula.getText().matches("\\d{1,}")){
                if(BuscarCedula(textCedula.getText())){
                    JOptionPane.showMessageDialog(this,"El paciente ya estaba registrado");
                    buscarPaciente v = new buscarPaciente(textCedula.getText());
                    Ventana.getPanel().add(v);
                    v.toFront();
                    v.setVisible(true);
                    vaciar();
                } else{
                    try {
                        Conexion cnn = new Conexion(Ventana.getruta());
                        Connection con = cnn.getConnection();
                        Statement st = con.createStatement();
                        String sql = "insert into Pacientes (cedula,nombre,apellido,sexo,direccion,numerotlf,descripcion,Aspecto,CedulaTitular,Empresa,Area) values (?,?,?,?,?,?,?,?,?,?,?)";
                        PreparedStatement pst = con.prepareStatement(sql);
                        pst.setString(1, textCedula.getText());
                        pst.setString(2, textNombre.getText());
                        pst.setString(3, textApellido.getText());
                        pst.setString(4, buttonGroup1.getSelection().getActionCommand());
                        pst.setString(5, jTextAreaDireccion.getText());
                        pst.setString(6, textTelefono.getText());
                        pst.setString(7, jTextdescripcion.getText());
                        pst.setString(8, (String) jComboBox1.getSelectedItem());
                        pst.setString(9, CedulaT.getText());
                        pst.setString(10, empresa.getText());
                        pst.setString(11, Departamento.getText());
                        int n = pst.executeUpdate();
                        if(n>0){
                            JOptionPane.showMessageDialog(this, "DATOS GUARDADOS CORRECTAMENTE");
                            cnn.Desconexion();
                            vaciar();
                        }
                        con.close();
                    } catch (SQLException e) {
                        JOptionPane.showMessageDialog(this, "LOS DATOS NO HAN SIDO GUARDADOS CORRECTAMENTE", "Error", JOptionPane.ERROR_MESSAGE);
                    }
                }
            } else {
                textCedula.setBackground(Color.pink);
                JOptionPane.showMessageDialog(this,"No introduzca letras o simbolos en el numero de cedula");
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        if((evt.getModifiers()&16)!=0){
            if(((String)jComboBox1.getSelectedItem()).equals("Familiar de Trabajador")){
                CedulaT.setEnabled(true);
            } else {
                CedulaT.setEnabled(false);
            }
            if(((String)jComboBox1.getSelectedItem()).equals("Personal Empresa que hace vida en las instalaciones")||((String)jComboBox1.getSelectedItem()).equals("Otras Instituciones del estado")){
                empresa.setEnabled(true);
            } else {
                empresa.setEnabled(false);
            }
            if(((String)jComboBox1.getSelectedItem()).equals("Trabajador Titular")){
                Departamento.setEnabled(true);
            } else {
                Departamento.setEnabled(false);
            }
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void CedulaTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CedulaTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CedulaTActionPerformed

    private void CedulaTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CedulaTMouseClicked
        CedulaT.setBackground(Color.white);
    }//GEN-LAST:event_CedulaTMouseClicked

    private void empresaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_empresaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_empresaMouseClicked

    private void empresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empresaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empresaActionPerformed

    private void DepartamentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DepartamentoMouseClicked
        Departamento.setBackground(Color.white);
    }//GEN-LAST:event_DepartamentoMouseClicked

    private void DepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DepartamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DepartamentoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CedulaT;
    private javax.swing.JTextField Departamento;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField empresa;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextAreaDireccion;
    private javax.swing.JTextArea jTextdescripcion;
    private javax.swing.JRadioButton radioF;
    private javax.swing.JRadioButton radioM;
    private javax.swing.JTextField textApellido;
    private javax.swing.JTextField textCedula;
    private javax.swing.JTextField textNombre;
    private javax.swing.JTextField textTelefono;
    // End of variables declaration//GEN-END:variables
}
