/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import conexiones.Conexion;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author aaron
 */
public class cerrarT extends javax.swing.JInternalFrame {

    private int id;
    private String fecha;
    public cerrarT() {
        initComponents();
        obtener();
    }
    private void obtener(){
        Connection con;
        Conexion conect = new Conexion(Ventana.getruta());
        con = conect.getConnection();
        String sql = "select Id from Informe ORDER BY Id DESC LIMIT 1";
        try {
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while(rs.next()){
                id=rs.getInt("Id");
            }
            con.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this,"problema con obtener los informes "+e);
        }
    }
    private void actualizar(){
        Connection con;
        Conexion conect = new Conexion(Ventana.getruta());
        con = conect.getConnection();
        String sql = "update Informe set Fecha_fin='"+fecha+"' where Id='"+id+"'";
        try {
            PreparedStatement pst = con.prepareStatement(sql);
            int n = pst.executeUpdate();
            JOptionPane.showMessageDialog(this,"Tabla cerrada de forma exitosa");
            con.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this,"problema intentando actualizar la tabla "+e);
        }
    }
    
    private void crear(){
        Connection con;
        Conexion conect = new Conexion(Ventana.getruta());
        con = conect.getConnection();
        String sql = "insert into Informe (Fecha_inicio) values (?)";
        try {
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1,fecha);
            int n = pst.executeUpdate();
            JOptionPane.showMessageDialog(this,"Tabla nueva creada de forma exitosa");
            con.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this,"problema intentando crear la tabla nueva "+e);
        }
    }
    
    private boolean comprobar(){
        int c = 0;
        if(textdia.getText().isEmpty()){
            textdia.setBackground(Color.pink);
            c++;
        }
        if(textmes.getText().isEmpty()){
            textmes.setBackground(Color.pink);
            c++;
        } 
        if(textanio.getText().isEmpty()){
            textanio.setBackground(Color.pink);
            c++;
        }
        if(!textdia.getText().matches("\\d{1,}")&& !textdia.getText().isEmpty()){
            textdia.setBackground(Color.pink);
            c++;
            JOptionPane.showMessageDialog(this,"No introduzca letras en el dia");
        }
        if(!textmes.getText().matches("\\d{1,}")&& !textmes.getText().isEmpty()){
            textmes.setBackground(Color.pink);
            c++;
            JOptionPane.showMessageDialog(this,"No introduzca letras en el mes");
        }
        if(!textanio.getText().matches("\\d{1,}")&& !textanio.getText().isEmpty()){
            textanio.setBackground(Color.pink);
            c++;
            JOptionPane.showMessageDialog(this,"No introduzca letras en el año");
        }
        if(textmes.getText().matches("\\d{1,}")&&textdia.getText().matches("\\d{1,}")){
            if(Integer.parseInt(textmes.getText())==2&&Integer.parseInt(textdia.getText())>29){
                textdia.setBackground(Color.pink);
                c++;
                JOptionPane.showMessageDialog(this,"Dia incorrecto");
            }  
        }
        if(textdia.getText().matches("\\d{1,}")){
            if(Integer.parseInt(textdia.getText())>31||Integer.parseInt(textdia.getText())<1){
                textdia.setBackground(Color.pink);
                c++;
                JOptionPane.showMessageDialog(this,"Dia incorrecto");
            } 
        }
        if(textmes.getText().matches("\\d{1,}")){
            if(Integer.parseInt(textmes.getText())>12||Integer.parseInt(textmes.getText())<1){
                textmes.setBackground(Color.pink);
                c++;
                JOptionPane.showMessageDialog(this,"Mes incorrecto");
            }  
        }
        return c == 0;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        textdia = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        textmes = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        textanio = new javax.swing.JTextField();
        Cont = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setClosable(true);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("fecha de cierre");

        textdia.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textdia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textdiaMouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("/");

        textmes.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textmes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textmesMouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("/");

        textanio.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textanio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textanioMouseClicked(evt);
            }
        });

        Cont.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Cont.setText("jPasswordField1");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Contraseña");

        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(textdia, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(textmes, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(textanio, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Cont, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(textdia, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(textanio, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(textmes, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cont, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textdiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textdiaMouseClicked

    }//GEN-LAST:event_textdiaMouseClicked

    private void textmesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textmesMouseClicked

    }//GEN-LAST:event_textmesMouseClicked

    private void textanioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textanioMouseClicked

    }//GEN-LAST:event_textanioMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(comprobar()&&String.valueOf(Cont.getPassword()).equals("Bolipuertos_Gu@nt4")){
            fecha=textdia.getText()+"/"+textmes.getText()+"/"+textanio.getText();
            actualizar();
            crear();
        } else {
            JOptionPane.showMessageDialog(this, "Contraseña incorrecta");
        }       // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField Cont;
    private javax.swing.JButton jButton1;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JInternalFrame jInternalFrame2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField textCedula;
    private javax.swing.JTextField textCedula1;
    private javax.swing.JTextField textanio;
    private javax.swing.JTextField textdia;
    private javax.swing.JTextField textmes;
    // End of variables declaration//GEN-END:variables
}
