/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;


/**
 *
 * @author aaron
 */
public class InformeM extends javax.swing.JPanel{

    /**
     * Creates new form InformeM

     */
    public InformeM() {
        initComponents();
    }

    public void info(String cedu,String nom,String fecha,String sexo,String diag, String rp,String ind,String edad){
        Nombre1.setText(nom);
        Nombre2.setText(nom);
        Nombre3.setText(nom);
        Cedula1.setText(cedu);
        Cedula2.setText(cedu);
        Cedula3.setText(cedu);
        Edad.setText(edad);
        Edad2.setText(edad);
        Edad3.setText(edad);
        Fecha1.setText(fecha);
        fecha2.setText(fecha);
        fecha3.setText(fecha);
        Sexo1.setText(sexo);
        Sexo2.setText(sexo);
        Diag.setText(diag);
        Recipe.setText(rp);
        Indicaciones.setText(ind);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Nombre1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Cedula1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Edad = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        Fecha1 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        Diag = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        fecha2 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        Cedula2 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        Edad2 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        Sexo1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Recipe = new javax.swing.JTextArea();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        Nombre2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel38 = new javax.swing.JLabel();
        fecha3 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        Cedula3 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        Edad3 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        Sexo2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Indicaciones = new javax.swing.JTextArea();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        Nombre3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 0));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Informe Médico");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 125, 294, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Por el medio de la presente se hace constar ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 150, 249, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("que el/la paciente Sr.(a) :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 166, -1, -1));

        Nombre1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Nombre1.setText("...");
        jPanel1.add(Nombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 166, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("con C.I:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 187, -1, -1));

        Cedula1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Cedula1.setText("XXXXXXXXX");
        jPanel1.add(Cedula1, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 187, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("de");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 187, -1, -1));

        Edad.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Edad.setText("XX");
        jPanel1.add(Edad, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 187, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setText("años de edad");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 187, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setText("acude a consulta en este servicio médico el día ");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 208, 288, -1));

        Fecha1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Fecha1.setText("dd/mm/aaaa");
        jPanel1.add(Fecha1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 223, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setText("presentando impresión diagnóstica:");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 223, -1, -1));

        jLabel17.setText("Indicandose tratamiento ambulatorio.");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 381, 288, -1));

        jLabel18.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Sin nada más que agregar se despide");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 429, 308, -1));

        jLabel19.setBackground(new java.awt.Color(0, 0, 0));
        jLabel19.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setOpaque(true);
        jLabel19.setPreferredSize(new java.awt.Dimension(1, 1));
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 469, 294, -1));

        jLabel20.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Firma y sello médico");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 481, 294, -1));

        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("MPPS:__________________");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 506, 294, -1));

        Diag.setColumns(20);
        Diag.setLineWrap(true);
        Diag.setRows(5);
        jScrollPane3.setViewportView(Diag);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 244, 288, 131));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel23.setBackground(new java.awt.Color(0, 0, 0));
        jLabel23.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setOpaque(true);
        jLabel23.setPreferredSize(new java.awt.Dimension(1, 1));
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 129, 312, -1));

        fecha2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        fecha2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(fecha2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 136, 312, -1));

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel27.setText("Nombre del paciente:");
        jPanel2.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 157, 120, -1));

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel28.setText("<html>      <p>        Cédula de<br>identidad      </p> </html>");
        jPanel2.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 183, -1, -1));

        Cedula2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Cedula2.setText("XXXXXXXX");
        jPanel2.add(Cedula2, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 198, -1, -1));

        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel30.setText("Edad:");
        jPanel2.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 198, -1, -1));

        Edad2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Edad2.setText("XX");
        jPanel2.add(Edad2, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 198, -1, -1));

        jLabel32.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel32.setText("Sexo:");
        jPanel2.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 198, -1, -1));

        Sexo1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Sexo1.setText("Masculino");
        jPanel2.add(Sexo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 198, -1, -1));

        Recipe.setColumns(20);
        Recipe.setLineWrap(true);
        Recipe.setRows(5);
        jScrollPane1.setViewportView(Recipe);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 246, 320, 235));

        jLabel34.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel34.setText("Firma y sello médico");
        jPanel2.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 506, 186, -1));

        jLabel35.setBackground(new java.awt.Color(0, 0, 0));
        jLabel35.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel35.setOpaque(true);
        jLabel35.setPreferredSize(new java.awt.Dimension(1, 1));
        jPanel2.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 499, 142, -1));

        jLabel36.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel36.setText("Rp:");
        jPanel2.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 225, -1, -1));

        Nombre2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Nombre2.setText("...");
        jPanel2.add(Nombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 157, -1, -1));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel38.setBackground(new java.awt.Color(0, 0, 0));
        jLabel38.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel38.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel38.setOpaque(true);
        jLabel38.setPreferredSize(new java.awt.Dimension(1, 1));
        jPanel4.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 128, 304, -1));

        fecha3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        fecha3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel4.add(fecha3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 135, 304, -1));

        jLabel42.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel42.setText("Nombre del paciente:");
        jPanel4.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 156, 124, -1));

        jLabel43.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel43.setText("<html>      <p>        Cédula de<br>identidad      </p> </html>");
        jPanel4.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 182, -1, -1));

        Cedula3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Cedula3.setText("XXXXXXXX");
        jPanel4.add(Cedula3, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 197, -1, -1));

        jLabel45.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel45.setText("Edad:");
        jPanel4.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 197, -1, -1));

        Edad3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Edad3.setText("XX");
        jPanel4.add(Edad3, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 197, -1, -1));

        jLabel47.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel47.setText("Sexo:");
        jPanel4.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 197, -1, -1));

        Sexo2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Sexo2.setText("Masculino");
        jPanel4.add(Sexo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 197, -1, -1));

        Indicaciones.setColumns(20);
        Indicaciones.setLineWrap(true);
        Indicaciones.setRows(5);
        jScrollPane2.setViewportView(Indicaciones);

        jPanel4.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 245, 300, 234));

        jLabel49.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel49.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel49.setText("Firma y sello médico");
        jPanel4.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 506, 286, -1));

        jLabel50.setBackground(new java.awt.Color(0, 0, 0));
        jLabel50.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel50.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel50.setOpaque(true);
        jLabel50.setPreferredSize(new java.awt.Dimension(1, 1));
        jPanel4.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 505, 142, -1));

        jLabel51.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel51.setText("Ind:");
        jPanel4.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 224, -1, -1));

        Nombre3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Nombre3.setText("...");
        jPanel4.add(Nombre3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 156, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Cedula1;
    private javax.swing.JLabel Cedula2;
    private javax.swing.JLabel Cedula3;
    private javax.swing.JTextArea Diag;
    private javax.swing.JLabel Edad;
    private javax.swing.JLabel Edad2;
    private javax.swing.JLabel Edad3;
    private javax.swing.JLabel Fecha1;
    private javax.swing.JTextArea Indicaciones;
    private javax.swing.JLabel Nombre1;
    private javax.swing.JLabel Nombre2;
    private javax.swing.JLabel Nombre3;
    private javax.swing.JTextArea Recipe;
    private javax.swing.JLabel Sexo1;
    private javax.swing.JLabel Sexo2;
    private javax.swing.JLabel fecha2;
    private javax.swing.JLabel fecha3;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables

}
